# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zwina <zwina@student.1337.ma>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/21 12:18:51 by zwina             #+#    #+#              #
#    Updated: 2023/06/15 13:13:22 by zwina            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:oldstable

RUN apt update -y && apt upgrade -y && \
    apt install redis -y

CMD ["redis-server", \
    "--protected-mode no", \
    "--bind 0.0.0.0", \
    "--maxmemory 2mb", \
    "--maxmemory-policy allkeys-lru"]
